---

- name: Running npm run ci-all...
  ansible.builtin.command:
    cmd: npm install typescript -g

- name: Cloning PerlNavigator repo...
  ansible.builtin.git:
    repo: https://github.com/bscan/PerlNavigator
    dest: /opt/nvim/repos/PerlNavigator/

- name: Running npm run ci-all...
  ansible.builtin.command:
    cmd: npm run ci-all
    chdir: /opt/nvim/repos/PerlNavigator/

- name: Running tsc in server folder...
  ansible.builtin.command:
    cmd: tsc
    chdir: /opt/nvim/repos/PerlNavigator/server/
