#!/bin/bash

user_info() {
    echo "User: $(id | awk '{print $1" "$2}')"
}

hostname_info() {
    echo "Hostname: $(hostname)"
}

uname_info() {
    echo "Kernel release: $(uname --kernel-release)"
    #echo "Kernel version: $(uname --kernel-version)"
}

cpu_info() {
    lscpu | awk -F ':' '/^Model name/ {print $1":"$2}'
}

lsb_info() {
    lsb_release -a 2>/dev/null | awk -F ':' '/^Description/ {print $1":"$2}'
}

mem_info() {
    free -h | awk '/^Mem/ {print $1" "$2}'
}

wmctrl_info() {
    wmctrl_exists="$(which wmctrl)"
    if [[ -n $wmctrl_exists ]]; then
        wmctrl -m | awk '/^Name/ {print "WM "$1" "$2}'
    fi
}

extra_functions=(
    user_info
    hostname_info
    lsb_info
    uname_info
    cpu_info
    mem_info
    wmctrl_info
)
