---

- name: Build neovim...
  tags:
    - build
  block:
    - name: Install dependencies...
      ansible.builtin.apt:
        name: '{{ pkg_name }}'
      loop:
        - ninja-build
        - gettext
        - libtool
        - libtool-bin
        - autoconf
        - automake
        - cmake
        - g++
        - pkg-config
        - unzip
        - curl
        - doxygen
      loop_control:
        loop_var: pkg_name

    - name: Make necessary directories...
      ansible.builtin.file:
        path: '{{ directory_name }}'
        state: directory
        mode: '0755'
      loop:
        - /opt/nvim/
        - /opt/nvim/repos/
      loop_control:
        loop_var: directory_name

    - name: Deleting repository directory...
      ansible.builtin.file:
        path: /opt/nvim/repos/neovim/
        state: absent

    - name: Clone the repo...
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim
        dest: /opt/nvim/repos/neovim/

    - name: Making neovim...
      ansible.builtin.command:
        cmd: make CMAKE_BUILD_TYPE=Release
        chdir: /opt/nvim/repos/neovim/

    - name: Installing neovim...
      ansible.builtin.command:
        cmd: make install
        chdir: /opt/nvim/repos/neovim/

    - name: Running nvim version (will fail if nvim does not exists in the system)...
      ansible.builtin.command:
        cmd: nvim --version
      register: nvim_version

    - name: NEOVIM SUCCESSFULLY INSTALLED...
      ansible.builtin.debug:
        msg: '{{ nvim_version.stdout_lines }}'

...
