---

- name: Configure neovim...
  tags:
    - config
  become: true
  become_user: '{{ user }}'
  block:

    - name: Install dependencies...
      ansible.builtin.apt:
        name: '{{ pkg_name }}'
      loop:
        - xclip
      loop_control:
        loop_var: pkg_name

    - name: Making necessary directories...
      ansible.builtin.file:
        path: '{{ user_home }}/.config/nvim'
        state: directory
        mode: '0755'

    - name: Cloning config repo...
      ansible.builtin.git:
        repo: '{{ nvim_config_repo }}'
        dest: '{{ user_home }}/.config/nvim'

    - name: Sync all the plugins with packer...
      ansible.builtin.command: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

    - name: Install all the plugins with packer...
      ansible.builtin.command: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall'

    # # TODO: wtf
    # - name: Sync again because luasnip...
    #   ansible.builtin.command: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

...
