#!/usr/bin/env bash
#

help='
Options:

[-i] install fonts
[-l] list installed fonts
[-e] explain
[-h] help
'
explain='
General:

-i:
Install nerd fonts

-l:
ls ~/.local/share/fonts/

-e:
This

-h:
Help
'

install=false
list=false

getopts_executed=false
while getopts "ileh" opt; do
    case $opt in
    i) install=true ;;
    l) list=true ;;
    e) echo "$explain" && exit 0 ;;
    h) echo "$help" && exit 0 ;;
    *) echo "$help" && exit 1 ;;
    esac
    getopts_executed=true
done

if ! $getopts_executed; then
    echo "No option given!" >&2
    echo "$help"
    exit 1
fi

install_path="$HOME/.local/share/fonts"

install_nerd_fonts() {
    mkdir -p "$install_path"
    install_nerd_font() {
        rm -rf "$install_path/${1}Nerd"
        mkdir -p "$install_path/${1}Nerd"
        wget -O "$install_path/${1}Nerd.tar.xz" "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$1.tar.xz"
        tar -xf "$install_path/${1}Nerd.tar.xz" -C "$install_path/${1}Nerd"
        rm -f "$install_path/${1}Nerd.tar.xz"
    }
    fonts=(
        SourceCodePro
        Cousine
        JetBrainsMono
        Lilex
        DejaVuSansMono
    )

    for font in "${fonts[@]}"; do
        install_nerd_font "$font"
    done
}

if $install; then
    install_nerd_fonts
    fc-cache -rf
    exit 0
fi

if $list; then
    ls -1 "$HOME/.local/share/fonts"
    exit 0
fi
