#!/usr/bin/env bash
#

help='
Options:

[-i] install fonts
[-l] list installed fonts
[-e] explain
[-h] help
'
explain='
General:

-i:
Install nerd fonts

-l:
ls ~/.local/share/fonts/

-e:
This

-h:
Help
'

install=false
list=false

getopts_executed=false
while getopts "ileh" opt; do
    case $opt in
    i) install=true ;;
    l) list=true ;;
    e) echo "$explain" && exit 0 ;;
    h) echo "$help" && exit 0 ;;
    *) echo "$help" && exit 1 ;;
    esac
    getopts_executed=true
done

if ! $getopts_executed; then
    echo "No option given!" >&2
    echo "$help"
    exit 1
fi

minimal=false
if [[ -f "$HOME/.minimal_environment" ]]; then
    minimal=true
fi

install_path="$HOME/.local/share/fonts"

install_nerd_fonts() {
    mkdir -p "$install_path"
    install_nerd_font() {
        rm -rf "$install_path/${1}Nerd"
        mkdir -p "$install_path/${1}Nerd"
        wget -O "$install_path/${1}Nerd.tar.xz" "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$1.tar.xz"
        tar -xf "$install_path/${1}Nerd.tar.xz" -C "$install_path/${1}Nerd"
        rm -f "$install_path/${1}Nerd.tar.xz"
    }
    fonts=(
        SourceCodePro
        Cousine
        JetBrainsMono
        Lilex
        DejaVuSansMono
        FiraMono
    )

    for font in "${fonts[@]}"; do
        install_nerd_font "$font"
    done
}

install_normal_fonts() {
    mkdir -p "$install_path"

    rm -rf "$install_path/JetBrainsMono"
    mkdir -p "$install_path/JetBrainsMono"
    wget -O "$install_path/JetBrainsMono.zip" 'https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip'
    unzip -d "$install_path/JetBrainsMono" "$install_path/JetBrainsMono.zip"
    rm -f "$install_path/JetBrainsMono.zip"
}

if $install; then
    if ! $minimal; then
        install_nerd_fonts
    else
        install_normal_fonts
    fi

    fc-cache -rf
    exit 0
fi

if $list; then
    ls -1 "$HOME/.local/share/fonts"
    exit 0
fi
