#!/bin/bash
#


help='
Options:

[-i] install fonts
[-l] list installed fonts
[-e] explain
[-h] help
'
explain='
General:

-i:
Install nerd fonts

-l:
ls "$HOME/.local/share/fonts/"

-e:
This

-h:
Help
'

install=false
list=false

getopts_executed=false
while getopts "ileh" opt; do
	case $opt in
        i) install=true ;;
        l) list=true ;;
        e) echo "$explain" && exit 0;;
        h) echo "$help" && exit 0;;
        *) echo "$help" && exit 1;;
	esac
    getopts_executed=true
done

if ! $getopts_executed; then
    echo "No option given!" >&2
    echo "$help"
    exit 1
fi

if $install;then
    install_path="$HOME/.local/share/fonts"
    mkdir -p "$install_path"
    install_font() {
        rm -rf "$install_path/$1"
        mkdir -p "$install_path/$1"
        wget -O "$install_path/$1.tar.xz" "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$1.tar.xz"
        tar -xf "$install_path/$1.tar.xz" -C "$install_path/$1"
        rm -f "$install_path/$1.tar.xz"
    }
    fonts=(
        SourceCodePro
        Cousine
        JetBrainsMono
        Lilex
        DejaVuSansMono
        FiraMono
    )

    for font in "${fonts[@]}"; do
        install_font $font
    done

    fc-cache -f
    exit 0
fi

if $list; then
    ls -1 "$HOME/.local/share/fonts"
    exit 0
fi
