#!/bin/bash
set -e

help='
Options:

[-i] to install themes
[-t <theme.json>] to set a theme
[-l] list installed themes
[-c] current used configs
[-f] to set flatpak themes (req sudo)
[-e] explain
[-h] help
'
explain='
Idiotically made gtk manager in pure bash.

Dependencies:
jq, git

General:
The operations are *just* for the current user.
sudo is not required for manipulating user level gtk.
This will not manage system wide gtk.
Use sudo for important things!
This program is very high level and for all applications to work
consistenly after changing a theme you need to logout/login.
The major problem is the the cursor pointer:
There are some things as a workaround, like:
´xinput disable <your mouse id> && xinput enable <your mouse id>´
(You can obtain the mouse id with ´xinput list´)
but a lot of applications keep a cache for certain elements and
the old cursor will still showing, e.g Chrome.
So restart your display manager,
is the easiest way to not depend on the applications.
This will not do anything related to gtk 1.

-i:
Install gtk themes, icons and cursors defined in the 'gtk_installers.sh' file.
There is not <<updating>>, updating *is* reinstalling. (1)
Installers are bash *idempotent* (cause (1)) functions.
In general the functions download something in /tmp and copy the content
to $HOME/.icons or $HOME/.themes

-t:
The json file needs to be in the form of:
{
    "theme": "<theme installed>",
    "icons": "<icons installed>",
    "cursor": "<cursor installed>"
}
Read the json file using jq, then create all three gtk setting files:
- $HOME/.config/.gtkrc-2.0
- $HOME/.config/gtk-3.0/settings.ini
- $HOME/.config/gtk-4.0/settings.ini
Set the cursor theme as default for good behaviour in:
- $HOME/.icons/default/<the content of the cursor theme directory>

-c:
cat this three files:
- $HOME/.config/.gtkrc-2.0
- $HOME/.config/gtk-3.0/settings.ini
- $HOME/.config/gtk-4.0/settings.ini

-f:
Set the selected gtk for flatpak.
sudo is required to set flatpak themes :/

-l:
ls this two directories:
- $HOME/.themes
- $HOME/.icons

-e:
This

-h:
Help

'

install=false
list=false
config=false
flatpak=false
gtk_theme=

getopts_executed=false
while getopts "flihcet:" opt; do
	case $opt in
        f) flatpak=true ;;
        l) list=true ;;
        i) install=true ;;
        c) config=true ;;
        t) gtk_theme="$OPTARG" ;;
        e) echo "$explain" && exit 0;;
        h) echo "$help" && exit 0;;
        *) echo "$help" && exit 1;;
	esac
    getopts_executed=true
done

if ! $getopts_executed; then
    echo "No option given!" >&2
    echo "$help"
    exit 1
fi

if $install; then
    mkdir -p "$HOME/.icons" "$HOME/.themes"
    source "$HOME/mybash/managers/lib/gtk_installers.sh"
    for inst_function in "${installers[@]}"; do
        "$inst_function"
    done
    exit 0
fi

if $list; then
    echo "THEMES"
    if [[ -d "$HOME/.themes" ]]; then
        ls -1 "$HOME/.themes"
    fi
    echo ""
    echo "ICONS"
    if [[ -d "$HOME/.icons" ]]; then
        ls -I "default" -1 "$HOME/.icons"
    fi
    exit 0
fi

if $config; then
    echo "GTK 2"
    if [[ -f "$HOME/.config/.gtkrc-2.0" ]]; then
        cat "$HOME/.config/.gtkrc-2.0"
    fi
    echo "GTK 3"
    if [[ -f "$HOME/.config/gtk-3.0/settings.ini" ]]; then
        cat "$HOME/.config/gtk-3.0/settings.ini"
    fi
    echo "GTK 4"
    if [[ -f "$HOME/.config/gtk-4.0/settings.ini" ]]; then
        cat "$HOME/.config/gtk-4.0/settings.ini"
    fi
    exit 0
fi

# Check for errors
if [[ -z $gtk_theme ]]; then
	echo "No theme specified!" >&2
	exit 1
fi

if [[ ! -f "$gtk_theme" ]]; then
    echo "The json file does not exists!" >&2
    exit 1
fi

theme="$(jq -rM .theme < "$gtk_theme")"
icons="$(jq -rM .icons < "$gtk_theme")"
cursor="$(jq -rM .cursor < "$gtk_theme")"
if [[ -z $theme ]] ||
    [[ -z $icons ]] ||
    [[ -z $cursor ]] ||
    [[ $theme = "null" ]] ||
    [[ $icons = "null" ]] ||
    [[ $cursor = "null" ]]; then
    echo "The json is not well defined!" >&2
    exit 1
fi

if [[ ! -d "$HOME/.themes/$theme" ]] ||
    [[ ! -d "$HOME/.icons/$icons" ]] ||
    [[ ! -d "$HOME/.icons/$cursor" ]]; then
    echo "Some themes do not exists!" >&2
    exit 1
fi

# Define the new gtks files
gtk2="
gtk-application-prefer-dark-theme = 1
gtk-theme-name = \"$theme\"
gtk-icon-theme-name = \"$icons\"
gtk-cursor-theme-name = \"$cursor\"
"
gtk34="
[Settings]
gtk-application-prefer-dark-theme = 1
gtk-theme-name = $theme
gtk-icon-theme-name = $icons
gtk-cursor-theme-name = $cursor
"
# Create directories
mkdir -p "$HOME/.config" "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
echo "$gtk2" > "$HOME/.config/.gtkrc-2.0"
echo "$gtk34" > "$HOME/.config/gtk-3.0/settings.ini"
echo "$gtk34" > "$HOME/.config/gtk-4.0/settings.ini"

# Copy the cursor theme to the default directory, first delete the previous one
mkdir -p "$HOME/.icons/default"
rm -rf "$HOME/.icons/default/"*
cp -r "$HOME/.icons/$cursor/"* "$HOME/.icons/default"
