#!/usr/bin/env bash
#
#

export PATH="$HOME/environment/bin:$HOME/environment/managers:$PATH:$HOME/.local/bin"
sys_manager -n
sys_manager -u

rm -rf "$HOME/.config/i3" "$HOME/.bashrc" "$HOME/.profile"
theme_manager -w
font_manager -i
theme_manager

