#!/usr/bin/env bash
#
#
set -e

help='
Options:

[-u] upgrade system
[-n] compile neovim
[-e] explain
[-h] help
'

explain='
General:
Common uses that I do with my system.

-u:
Upgrade the system: apt, pip, flatpak packages

-n:
Build neovim nightly

-e
This

-h
Help
'
source "${HOME}/environment/managers/lib/sys_packages.sh"
source "${HOME}/environment/managers/lib/sys_installers.sh"

upgrade=false
neovim=false

getopts_executed=false
while getopts "uenh" opt; do
    case $opt in
    u) upgrade=true ;;
    n) neovim=true ;;
    e) echo "${explain}" && exit 0 ;;
    h) echo "${help}" && exit 0 ;;
    *) echo "${help}" && exit 1 ;;
    esac
    getopts_executed=true
done

if ! $getopts_executed; then
    echo "No option given..."
    echo "${help}"
    exit 1
fi

print_separator() {
    echo -e "........................."
}

get_root_access() {
    sudo -v
}

install_apt() {
    sudo apt-get -qq update
    sudo apt-get -qq dist-upgrade -y
    sudo apt-get -qq --with-new-pkgs upgrade -y
    sudo apt-get -qq install -y "${apt_common_packages[@]}"
}

install_pip() {
    sudo apt-get -qq install pipx
    pipx install -U "${pip_packages[@]}"
}

install_cargo() {
    cargo install "${cargo_packages[@]}" >/dev/null
}

update_flatpak() {
    sudo flatpak update -y >/dev/null
}

cleanup() {
    sudo apt-get -qq remove --purge -y steam wine
    sudo apt-get -qq autoremove --purge -y

    rm -f "${HOME}/.cache/dmenu_run"
    rm -f "${HOME}/dmenu_cache"
}

execute_task() {
    echo "${1}"
    "${2}"
    print_separator
}

if $upgrade; then
    execute_task "Asking for root..." get_root_access

    mkdir -p "$HOME/images/" "$HOME/projects/" "$HOME/bin/"

    execute_task "Updating apt packages..." install_apt

    execute_task "Updating pip packages..." install_pip

    execute_task "Updating flatpak packages..." update_flatpak
    execute_task "Updating cargo packages..." install_cargo

    for independent_installer in "${independent_installers[@]}"; do
        execute_task "$independent_installer" "$independent_installer"
    done

    execute_task "Cleaning up..." cleanup

    echo "Done! Remember to reboot your pc!"

    exit 0
fi

if $neovim; then
    execute_task "Asking for root..." get_root_access
    sudo "$HOME/environment/managers/lib/sys_neovim.sh"
    exit 0
fi
