#!/usr/bin/env bash
help='
Options:

[-w] update wallpapers
[-e] explain
[-h] help
'

explain='
Reload environment.

- Copy the files inside ~/environment/dotfiles/ to ~/.dotfiles_stow
- Stow the content of ~/.dotfiles_stow
- Reload i3, dunst, picom and clean dmenu cache
- Set a new wallpaper

-w:
Clone the wallpapers repo

-e:
This

-h:
Help

'

wallpaper=false
while getopts "whe:" opt; do
    case $opt in
    w) wallpaper=true ;;
    e) echo "$explain" && exit 0 ;;
    h) echo "$help" && exit 0 ;;
    *) echo "$help" && exit 0 ;;
    esac
done

if $wallpaper; then
    rm -rf "$HOME/.wallpapers"
    mkdir -p "$HOME/.wallpapers"
    git clone "git@github.com:pablos123/.wallpapers.git" "$HOME/.wallpapers"
    exit 0
fi

# Create directories
mkdir -p "$HOME/.dotfiles_stow" "$HOME/bin"

# Copy the base content
rm -rf "$HOME/.dotfiles_stow/"*
cp -r "$HOME/environment/dotfiles/"* "$HOME/.dotfiles_stow"


# Stow the new files
(
    cd "$HOME/.dotfiles_stow" || exit 1
    stow --target="$HOME" --restow -- */
)

set_wallpaper

rm -f "$HOME/.cache/dmenu_run"
rm -f "$HOME/dmenu_cache"
i3-msg reload >/dev/null 2>&1
killall dunst >/dev/null 2>&1
killall flameshot >/dev/null 2>&1
killall picom >/dev/null 2>&1
sleep 0.5
picom --daemon >/dev/null 2>&1

