---

- name: Install a bunch of software...
  hosts: localhost
  tasks:

    - name: Including tasks from general role...
      tags:
        - packages
        - scripts
        - repos
        - gaming
        - clean
      ansible.builtin.include_role:
        name: general

...
