#!/bin/bash
# Save an image of your current monitors and blur it then, lock your screen.

scrot -o /tmp/lockerscreenshot.png
convert -blur 0x20 /tmp/lockerscreenshot.png /tmp/lockerscreenshot_blur.png
rm -f /tmp/lockerscreenshot.png
i3lock --no-unlock-indicator --nofork --ignore-empty-password -i /tmp/lockerscreenshot_blur.png
