#!/bin/bash
# This things were in my .profile but trying to access de display on the
# battery_notify (because the blacklist logic was bad)
# and some syntax error because shell != bash caused the GUI (after de DM login) to not load properly.
# A workaround I found was:
# the GUI start with startx with a simple .xinitrc that only executes i3.
# .profile will still be loaded with errors.
#
# My custom notifications.
if [[ -n "$(which cinecli)" ]]; then
    notify_movies() {
        local elcairo_delay=3
        ( (echo -e "notify-send --expire-time=60000 '📽️ $2 📽️' '\n$1'") | at "now + $elcairo_delay minutes") >/dev/null 2>&1
    }

    today_movies=$(cinecli shows --reverse --no_separator --no_extra_info today)
    notify_movies "$today_movies" "El Cairo movies today"

    day="$(date +'%A')"
    if [[ "$day" == "Monday" ]]; then
        week_movies=$(cinecli shows --reverse --no-separator --no-extra-info week)
        notify_movies "$week_movies" "El Cairo movies this week"
    elif [[ "$day" == "Friday" ]]; then
        weekend_movies=$(cinecli shows --reverse --no-separator --no-extra-info weekend)
        notify_movies "$weekend_movies" "El Cairo movies this weekend"
    fi
fi

check_batteries_delay=2
(echo "battery_notify" | at "now + $check_batteries_delay minutes") >/dev/null 2>&1
