---

- name: Installing root packages...
  become: true
  tags: packages
  block:
    - name: Installing apt packages...
      ansible.builtin.apt:
        pkg: '{{ apt_packages }}'

    - name: Installing flatpak packages...
      community.general.flatpak:
        name: '{{ flatpak_packages }}'

- name: Installing no root packages...
  become: true
  become_user: '{{ user }}'
  tags: packages
  block:
    - name: Installing pip packages...
      ansible.builtin.pip:
        name: '{{ pip_packages }}'

    - name: Installing cargo packages...
      community.general.cargo:
        name: '{{ cargo_packages }}'

    - name: Installing go packages...
      ansible.builtin.shell: '{{ go_packages }}'

- name: Scripts...
  become: true
  become_user: '{{ user }}'
  tags: scripts
  block:
    - name: Installing fonts...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/fonts.sh'

    - name: Installing fzf...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/fzf.sh'

    - name: Installing dunst...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/dunst.sh'

    - name: Installing gtk cursor, icons, themes...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/gtk.sh'

    - name: Installing i3...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/i3.sh'

    - name: Installing lazygit...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/lazygit.sh'

    - name: Installing cincli...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/cinecli.sh'

    - name: Configuring flatpak chrome...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/flatpak_chrome.sh'

- name: Repositories...
  become: true
  become_user: '{{ user }}'
  tags: repos
  block:
    - name: Creating projects directory...
      ansible.builtin.file:
        path: '{{ user_home }}/projects'
        state: directory
        mode: '0755'

    - name: Deleting .wallpapers because I reset every commit...
      ansible.builtin.file:
        path: '{{ user_home }}/.wallpapers'
        state: absent

    - name: Cloning repositories...
      ansible.builtin.git:
        repo: '{{ repository.repo }}'
        dest: '{{ repository.dest }}'
      loop: '{{ repositories }}'
      loop_control:
        loop_var: repository

    - name: Setting dotfiles...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/dotfiles.sh'

- name: Gaming stuff...
  tags: gaming
  block:
    - name: Uninstalling apt Steam...
      ansible.builtin.apt:
        name: steam
        state: absent

    - name: Installing Steam...
      community.general.flatpak:
        name: com.valvesoftware.Steam

    # the flatpack version is sandboxed and won't see /mnt or /media.
    # https://discourse.flathub.org/t/how-to-add-a-new-library-to-steam/2359
    - name: Installing Flatseal...
      community.general.flatpak:
        name: com.github.tchx84.Flatseal

    - name: Installing wine...
      ansible.builtin.apt:
        pkg: wine

- name: Cleaning...
  become: true
  become_user: '{{ user }}'
  tags: clean
  block:
    - name: Deleting dmenu cache...
      ansible.builtin.file:
        path: '{{ cache_file }}'
        state: absent
      loop:
        - '{{ user_home }}/.cache/dmenu_run'
        - '{{ user_home }}/dmenu_cache'
      loop_control:
        loop_var: cache_file

    - name: Deletings dowloaded files...
      ansible.builtin.script: '{{ user_home }}/environment/scripts/clean.sh'

...
