[manager]
show_hidden = true

[opener]
nvim = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
mpv = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]
zathura = [
    { run = 'zathura "$@"', orphan = true, for = "unix" },
]
sxiv = [
    { run = 'sxiv "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
    { mime = "text/*", use = "nvim" },
    { mime = "video/*", use = "mpv" },

    { name = "*.pdf", use = "zathura" },
    { name = "*.ps", use = "zathura" },
    { name = "*.cbz", use = "zathura" },
    { name = "*.cbr", use = "zathura" },
    { name = "*.djvu", use = "zathura" },

    { name = "*.png", use = "sxiv" },
    { name = "*.jpeg", use = "sxiv" },
    { name = "*.jpg", use = "sxiv" },
    { name = "*.webp", use = "sxiv" },
    { name = "*.gif", use = "sxiv" },
    { name = "*.svg", use = "sxiv" },
]

